In [16]:

#他ファイルからのimport
from cmath import cos
from gym.envs.registration import register#環境の登録
from stochastic_cliff_env import StochasticCliffWalkingEnv  # カスタム環境をインポート
from custom_maps import get_custom_map, get_custom_map_comp#カスタムマップをインポート
from policy_agent_comp import Policy1, Policy2, Agent
import math
import gym#カスタム環境をロードするために必要
import numpy as np
import os
from datetime import datetime
import pandas as pd
#プロット
import matplotlib.pyplot as plt

In [17]:
# カスタムマップの定義
custom_grid = get_custom_map_comp()

# 環境を登録
register(
    id='StochasticCliffWalking-v0',  # 環境ID
    entry_point='stochastic_cliff_env:StochasticCliffWalkingEnv',  # 環境クラスへのパス
    kwargs={'grid': custom_grid, 'slip_prob': 0.0},  # 環境に渡すパラメータ
)

# 登録済みのカスタム環境をロード
env = gym.make('StochasticCliffWalking-v0')


In [18]:
type(env.grid.shape[0]*env.grid.shape[1])

int

In [22]:
type(env.start)

numpy.ndarray

In [1]:
import numpy as np

# サンプルの四次元配列を作成（例）
new_theta2 = np.random.rand(2, 3, 4, 5)  # 2x3x4x5のランダム配列
new_theta2[0, 0, 0, 0] = np.nan  # np.nanを含むようにする

# 最大値を計算し、新しい配列を作成する関数
def normalize_4d_array(array):
    # 配列内の最大値（np.nanを除外）を取得
    max_value = np.nanmax(array)
    
    # 最大値を引いた新しい配列を作成
    result = array - max_value
    
    # np.nanの位置を保持
    result[np.isnan(array)] = np.nan
    return result

# 新しい配列を作成
result_array = normalize_4d_array(new_theta2)

print("元の配列:\n", new_theta2)
print("\n新しい配列:\n", result_array)


元の配列:
 [[[[       nan 0.88465969 0.01681632 0.89227439 0.97787531]
   [0.84914236 0.84866071 0.73369572 0.51847235 0.23052727]
   [0.9441063  0.95633022 0.12652192 0.48344771 0.66960624]
   [0.19106845 0.23198167 0.79542833 0.39673007 0.71364856]]

  [[0.30763728 0.57444179 0.90067028 0.80799423 0.76060659]
   [0.62565159 0.19727023 0.02052892 0.41101027 0.41011933]
   [0.66661614 0.90901604 0.63623618 0.37608442 0.10283674]
   [0.0842245  0.35097138 0.04932338 0.99655483 0.43853848]]

  [[0.99854505 0.626382   0.16891004 0.24158787 0.26405749]
   [0.74425612 0.79044523 0.43487205 0.45836324 0.33374422]
   [0.3125079  0.94439923 0.84290006 0.01067132 0.45619593]
   [0.36079426 0.18044944 0.06617248 0.20169777 0.0653299 ]]]


 [[[0.84500297 0.62749755 0.24937541 0.00370883 0.57295887]
   [0.00157891 0.00251294 0.19052446 0.79256062 0.21786548]
   [0.26708318 0.84609273 0.03118276 0.64918409 0.86959059]
   [0.06020229 0.07978029 0.80929703 0.56007224 0.28054791]]

  [[0.95619913 0.378735

In [9]:
new_theta2 = np.random.rand(2, 3, 4, 5)  # 2x3x4x5のランダム配列
new_theta2[0, 0, 0, 0] = np.nan  # np.nanを含むようにする
new_theta2[1, 0, 0, 0] = np.nan 
print(np.nanmax(new_theta2, axis=(2, 3), keepdims=True))
max_theta = np.nanmax(new_theta2, axis=(2, 3), keepdims=True)
new_theta2 = new_theta2 - max_theta  # 数値安定化した theta
print("元の配列:\n", new_theta2)

[[[[0.96856807]]

  [[0.99272452]]

  [[0.99380368]]]


 [[[0.84649369]]

  [[0.97808668]]

  [[0.97473966]]]]
元の配列:
 [[[[        nan -0.60707908 -0.71013276 -0.04838132 -0.79689087]
   [ 0.         -0.90225651 -0.22812759 -0.88504929 -0.63510686]
   [-0.61843593 -0.55230863 -0.69497773 -0.69950391 -0.4989733 ]
   [-0.17026878 -0.05858462 -0.06868422 -0.44913391 -0.47225057]]

  [[ 0.         -0.98194487 -0.40955828 -0.35412299 -0.10604665]
   [-0.63822287 -0.09415561 -0.17365901 -0.29881938 -0.14728647]
   [-0.05790153 -0.98506574 -0.08555773 -0.21903567 -0.6626853 ]
   [-0.77858721 -0.63031735 -0.38395673 -0.63670299 -0.15532292]]

  [[-0.55839676 -0.70617362 -0.96167248 -0.20617017 -0.75330388]
   [-0.93060953 -0.60386393 -0.75733505 -0.5740324   0.        ]
   [-0.71109126 -0.29199965 -0.67689995 -0.12632597 -0.14157022]
   [-0.49484572 -0.53207922 -0.97616663 -0.16872652 -0.98025269]]]


 [[[        nan -0.09443941 -0.15805223 -0.54969329 -0.18937085]
   [-0.65803898 -0.21028833 -

In [11]:
not(np.isnan(new_theta2[0][0][0][0]))

False

In [13]:
new_theta2[0][0][0][0]

nan

In [15]:
from policy_agent_comp import Agent, Policy1, Policy2
from custom_maps import get_custom_map, get_custom_map_comp
custom_grid = get_custom_map_comp()
p1 = Policy1(grid=custom_grid)
p1.softmax_probs()

array([[[0.        , 0.25      , 0.25      , 0.        ],
        [0.        , 0.25      , 0.25      , 0.        ]],

       [[0.        , 0.16666667, 0.16666667, 0.16666667],
        [0.        , 0.16666667, 0.16666667, 0.16666667]],

       [[0.        , 0.16666667, 0.16666667, 0.16666667],
        [0.        , 0.16666667, 0.16666667, 0.16666667]],

       [[0.        , 0.16666667, 0.16666667, 0.16666667],
        [0.        , 0.16666667, 0.16666667, 0.16666667]],

       [[0.        , 0.16666667, 0.16666667, 0.16666667],
        [0.        , 0.16666667, 0.16666667, 0.16666667]],

       [[0.        , 0.        , 0.25      , 0.25      ],
        [0.        , 0.        , 0.25      , 0.25      ]],

       [[0.16666667, 0.16666667, 0.16666667, 0.        ],
        [0.16666667, 0.16666667, 0.16666667, 0.        ]],

       [[0.125     , 0.125     , 0.125     , 0.125     ],
        [0.125     , 0.125     , 0.125     , 0.125     ]],

       [[0.125     , 0.125     , 0.125     , 0.125     ]